export const selectionQuestions = [
  {
    id: 'platform',
    title: '你的主要直播平台是？',
    description: '选择当前最主要的成交平台',
    type: 'single',
    required: true,
    options: [
      { id: 'douyin', label: '抖音' },
      { id: 'kuaishou', label: '快手' },
      { id: 'xiaohongshu', label: '小红书' },
      { id: 'wechat-channels', label: '视频号' },
      { id: 'taobao-live', label: '淘宝直播' },
      { id: 'other', label: '其他平台' },
    ],
  },
  {
    id: 'content-direction',
    title: '你的账号内容方向是？',
    description: '我们会据此判断粉丝更容易接受的货品表达方式',
    type: 'single',
    required: true,
    options: [
      { id: 'jewelry', label: '珠宝垂类', criteria: { keywords: ['培育钻', '白钻', '彩钻'] } },
      { id: 'fashion-beauty', label: '穿搭美妆', criteria: { types: ['耳钉', '耳圈', '项链', '手链'], keywords: ['小清新', '经典', '百搭'] } },
      { id: 'romance', label: '婚恋情感', criteria: { types: ['女戒', '戒指', '男戒'], keywords: ['求婚', '纪念', '对戒', '四爪', '六爪'] } },
      { id: 'lifestyle', label: '生活方式', criteria: { types: ['耳钉', '项链', '手链'], keywords: ['日常', '简约', '小清新'] } },
      { id: 'gifting', label: '礼赠', criteria: { types: ['吊坠', '项链', '耳钉'], keywords: ['心形', '蝴蝶', '经典'] } },
      { id: 'general-commerce', label: '综合带货' },
    ],
  },
  {
    id: 'audience',
    title: '你的核心粉丝主要是哪类人群？',
    description: '选择直播间最主要的成交人群',
    type: 'single',
    required: true,
    options: [
      { id: 'age-18-25', label: '18–25 岁', criteria: { keywords: ['小清新', '时尚', '耳钉'] } },
      { id: 'age-25-35', label: '25–35 岁', criteria: { keywords: ['经典', '日常', '女戒'] } },
      { id: 'age-35-45', label: '35–45 岁', criteria: { keywords: ['祖母绿', '椭圆', '项链'] } },
      { id: 'age-45-plus', label: '45 岁以上', criteria: { keywords: ['经典', '铂金', '宴会'] } },
      { id: 'high-net-worth', label: '高净值人群', criteria: { keywords: ['粉钻', '彩钻', '重工', '高奢'], pricePreference: 'high' } },
    ],
  },
  {
    id: 'live-goal',
    title: '本场直播最重要的目标是？',
    description: '系统会按目标调整货盘排序',
    type: 'single',
    required: true,
    options: [
      { id: 'acquisition', label: '拉新引流', criteria: { pricePreference: 'low', requireInStock: true } },
      { id: 'volume', label: '冲成交量', criteria: { pricePreference: 'low', requireInStock: true } },
      { id: 'aov', label: '提高客单价', criteria: { pricePreference: 'high' } },
      { id: 'profit', label: '提高利润', criteria: { minCommission: 15 } },
      { id: 'brand-session', label: '品牌专场', criteria: { keywords: ['原创', '经典', '系列', '高奢'] } },
    ],
  },
  {
    id: 'price-range',
    title: '你希望主推哪个成交价格带？',
    description: '请选择直播间最容易成交的客单区间',
    type: 'single',
    required: true,
    options: [
      { id: 'under-5000', label: '5,000 元以内', criteria: { maxPrice: 5000 } },
      { id: '5000-10000', label: '5,000–10,000 元', criteria: { minPrice: 5000, maxPrice: 10000 } },
      { id: '10000-20000', label: '10,000–20,000 元', criteria: { minPrice: 10000, maxPrice: 20000 } },
      { id: '20000-50000', label: '20,000–50,000 元', criteria: { minPrice: 20000, maxPrice: 50000 } },
      { id: 'over-50000', label: '50,000 元以上', criteria: { minPrice: 50000 } },
      { id: 'flexible', label: '预算灵活' },
    ],
  },
  {
    id: 'categories',
    title: '你希望本场选择哪些品类？',
    description: '可多选，选好后点击下一题',
    type: 'multiple',
    required: true,
    options: [
      { id: 'rings', label: '戒指', criteria: { types: ['女戒', '戒指', '男戒'] } },
      { id: 'necklaces', label: '项链 / 吊坠', criteria: { types: ['项链', '吊坠'] } },
      { id: 'earwear', label: '耳饰', criteria: { types: ['耳钉', '耳圈', '耳饰', '耳扣', '耳吊', '耳钩', '耳线'] } },
      { id: 'bracelets', label: '手链 / 脚链', criteria: { types: ['手链', '脚链'] } },
      { id: 'sets', label: '套装', criteria: { keywords: ['套装', '套系', '打孔套装'] } },
    ],
  },
  {
    id: 'selling-points',
    title: '你的直播间更容易讲哪类卖点？',
    description: '可选择多个擅长表达的方向',
    type: 'multiple',
    required: true,
    options: [
      { id: 'carat-value', label: '大克拉性价比', criteria: { minCarat: 1, keywords: ['克拉', '高性价比'] } },
      { id: 'classic', label: '经典百搭', criteria: { keywords: ['经典', '四爪', '六爪', '圆形'] } },
      { id: 'original', label: '原创设计', criteria: { keywords: ['原创', '异形', '马眼', '蝴蝶', '复古'] } },
      { id: 'colored-diamond', label: '粉钻 / 彩钻', criteria: { keywords: ['粉钻', '黄钻', '蓝宝', '彩宝'] } },
      { id: 'proposal', label: '求婚纪念', criteria: { types: ['女戒', '戒指', '男戒'], keywords: ['求婚', '纪念', '四爪', '六爪'] } },
      { id: 'banquet', label: '宴会高奢', criteria: { keywords: ['宴会', '高奢', '重工', '彩钻'], pricePreference: 'high' } },
      { id: 'education', label: '培育钻知识科普', criteria: { keywords: ['培育白钻', '培育粉钻', '培育黄钻'] } },
    ],
  },
  {
    id: 'supply-mode',
    title: '你能接受哪些合作与供货方式？',
    description: '可多选，系统会优先匹配供货条件',
    type: 'multiple',
    required: true,
    options: [
      { id: 'in-stock', label: '只要现货', criteria: { requireInStock: true } },
      { id: 'preorder', label: '接受预售' },
      { id: 'custom', label: '支持定制', criteria: { keywords: ['定制', 'DIY', '戒指'] } },
    ],
  },
  {
    id: 'product-style',
    title: '你更想在直播间呈现哪类产品？',
    description: '可多选，用于建立直播间的视觉风格',
    type: 'multiple',
    required: true,
    options: [
      { id: 'gem-color', label: '彩宝 / 彩钻', criteria: { keywords: ['彩宝', '粉钻', '黄钻', '蓝宝', '彩粉色'] } },
      { id: 'daily', label: '日常百搭', criteria: { types: ['耳钉', '项链', '手链'], keywords: ['日常', '百搭', '小清新', '简约'] } },
      { id: 'luxury-inspired', label: '大牌经典感', criteria: { keywords: ['卡家', 'T家', '四爪', '六爪', '经典'] } },
      { id: 'ceremony', label: '婚恋仪式感', criteria: { types: ['女戒', '戒指', '男戒'], keywords: ['求婚', '纪念', '心形'] } },
      { id: 'statement', label: '宴会重工', criteria: { keywords: ['宴会', '重工', '高奢'], pricePreference: 'high' } },
      { id: 'niche', label: '小众原创', criteria: { keywords: ['原创', '异形', '马眼', '蝴蝶', '复古'] } },
    ],
  },
  {
    id: 'metal',
    title: '你偏好哪些金属颜色与材质？',
    description: '可多选，不确定时选择不限',
    type: 'multiple',
    required: true,
    options: [
      { id: '18k-yellow', label: '18K 黄', criteria: { materials: ['18K黄'] } },
      { id: '18k-white', label: '18K 白', criteria: { materials: ['18K白'] } },
      { id: 'pt950', label: 'Pt950 铂金', criteria: { materials: ['Pt950'] } },
      { id: 'rose-or-two-tone', label: '玫瑰金 / 双色', criteria: { materials: ['18K红', '18K红白'] } },
      { id: 'any-metal', label: '不限材质' },
    ],
  },
  {
    id: 'commission',
    title: '你的最低佣金要求是？',
    description: '部分商品佣金待确认，系统会优先展示已满足条件的商品',
    type: 'single',
    required: true,
    options: [
      { id: 'commission-10', label: '10% 以上', criteria: { minCommission: 10 } },
      { id: 'commission-15', label: '15% 以上', criteria: { minCommission: 15 } },
      { id: 'commission-20', label: '20% 以上', criteria: { minCommission: 20 } },
      { id: 'commission-25', label: '25% 以上', criteria: { minCommission: 25 } },
      { id: 'commission-flexible', label: '可协商' },
    ],
  },
  {
    id: 'shipping',
    title: '你期望的发货时效是？',
    description: '选择直播间可以对消费者承诺的最慢时效',
    type: 'single',
    required: true,
    options: [
      { id: 'within-48h', label: '48 小时内', criteria: { maxShippingDays: 2 } },
      { id: 'within-7d', label: '3–7 天', criteria: { maxShippingDays: 7 } },
      { id: 'within-15d', label: '8–15 天', criteria: { maxShippingDays: 15 } },
      { id: 'preorder-ok', label: '可接受更长预售' },
      { id: 'shipping-flexible', label: '时效可协商' },
    ],
  },
]
